
version: '3.8'

services:
  postgres:
    image: percona/postgresql:latest
    container_name: percona_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - integration-network
    volumes:
      - ./init_standalone/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql:
    image: percona/percona-server:latest
    container_name: percona_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    ports:
      - "3306:3306"
    networks:
      - integration-network
    volumes:
      - ./init_standalone/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: percona/percona-server-mongodb:latest
    container_name: percona_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    networks:
      - integration-network
    volumes:
      - ./init_standalone/mongodb_init.js:/docker-entrypoint-initdb.d/init.js

networks:
  integration-network:
    driver: bridge
